title: "AI Ã— Meteorology"
description: "Technical discussions on AI, atmospheric science, and extreme rainfall"

url: "https://imaduddin-faalih.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache


minimal_mistakes_skin: "default"
