title: "AI Ã— Meteorology"
description: "Technical discussions on AI, atmospheric science, and extreme rainfall"
remote_theme: "mmistakes/minimal-mistakes"


url: "https://imaduddin-faalih.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "default"
